title: Ismaël Lachheb
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Development Blog, Here, you will find blog post about Data Science, software development,
  my projects or FOSS related article.
author:
  name: "Ismaël Lachheb "
  email: "ismael.lachheb@protonmail.com"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  lachhebo


google_analytics:  UA-142589817-1 


source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Ismaël Lachheb"
year : "2019"
